[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyls"
version = "0.1.0"
description = "A simple Python ls implementation"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
pyls = "pyls.pyls:main"
